export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_HIDE = 'POPUP_HIDE';

export const POPUP_ADD_ADDRESS_OPEN = 'POPUP_ADD_ADDRESS_OPEN';
export const POPUP_ADD_ADDRESS_HIDE = 'POPUP_ADD_ADDRESS_HIDE';

export const POPUP_FILTER_OPEN = 'POPUP_FILTER_OPEN';
export const POPUP_FILTER_HIDE = 'POPUP_FILTER_HIDE';

export const COMMON_URL_REDIRECT_LOGIN = 'COMMON_URL_REDIRECT_LOGIN';

export const POPUP_POST_FREE_OPEN = 'POPUP_POST_FREE_OPEN';
export const POPUP_POST_FREE_HIDE = 'POPUP_POST_FREE_HIDE';
